### ISSUE TITLE
exclude bismillah in first ayah

### ISSUE THREAD

**Issue by hahn** [islamic-apps/alquran-api-client-php#2]
how to exclude bismillah in first ayah? 

example, when get first ayah of Albaqarah, API return بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ الم instead الم

thanks

**Comment by meezaan** [comment]
https://github.com/islamic-apps/alquran-web-app/blob/master/src/AlQuranCloud/Renderer/Surah.php. See line 39 here.

For that edition, the Bismillah is 39 characters, so you can just strip them out.

If $ayah contains بِسْمِ اللَّهِ الرَّحْمَٰنِ الرَّحِيمِ الم:

```php
$ayah = mb_substr($ayah->text, 39); // $ayah will now be just  الم
```
